### ISSUE TITLE
Split blobs

### ISSUE THREAD

**Issue by sandhilt** [Calindra/nonodo#106]
Split blobs to send to DAs

**Comment by sandhilt** [comment]
Repo: https://github.com/calindra/sequencer

**Comment by fabiooshiro** [comment]
nonodo celestia send my-movie.mp4

my-movie.mp4 has 10MB

split into 10 files of Xmb
let tx1 = 1mb
let tx2 = 1mb
let tx3 = 1mb
let tx4 = 1mb
let tx5 = 1mb
let tx6 = 1mb
let tx7 = 1mb
let tx8 = 1mb
let tx9 = 1mb
let tx10 = 1mb

let tx11 = [tx1, ..., tx10]

send the tx11 to celestia
