### ISSUE TITLE
inputter `retryCount` bug

### ISSUE THREAD

**Issue by ZzzzHui** [Calindra/nonodo#113]
The `retryCount` variable in the for loop here https://github.com/Calindra/nonodo/blob/441a98023dc6269002b5129d38fa4231ce9faee3/internal/sequencers/inputter/inputter.go#L95 is not incremented anywhere.

**Comment by sandhilt** [comment]
@ZzzzHui hi! I and @fabiooshiro decided for keep loop infinite and remove the retry functionality.
See more here: https://github.com/Calindra/nonodo/pull/121
Feel free for some additional feedback.

**Comment by ZzzzHui** [comment]
Hey @sandhilt 
Looks great!!
