### ISSUE TITLE
Support for Espresso Sequencer

### ISSUE THREAD

**Issue by fabiooshiro** [Calindra/nonodo#49]
Integrate support for the Espresso sequencer into the existing system to enhance functionality and performance. Implement the EspressoListener to add transactions as inputs using InputRepository.

**Comment by sandhilt** [comment]
https://github.com/Calindra/nonodo/blob/27e1bb514d24e899c6ab8a5440f192df747d5dc4/internal/rollup/rollup.go#L60

**Comment by fabiooshiro** [comment]
Basic support
https://github.com/Calindra/nonodo/pull/51
