### ISSUE TITLE
Espresso message sender

### ISSUE THREAD

**Issue by fabiooshiro** [Calindra/nonodo#57]
How to handle the message sender from espresso transaction?

**Comment by fabiooshiro** [comment]
https://eips.ethereum.org/EIPS/eip-712

**Comment by fabiooshiro** [comment]
references
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1559.md
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2718.md

**Comment by DiegoSena** [comment]
- Add nonce to transaction
- Check nonce when processing transaction
- Discuss where to store nonce in the node

**Comment by sandhilt** [comment]
- [ ] Add nonce to transaction
- [ ] Check nonce when processing transaction
- [ ] Discuss where to store nonce in the node

**Comment by ZzzzHui** [comment]
Here is an example of how to sign data with viem, similar to what Gui posted in Discord channel, but in more details:
https://viem.sh/docs/actions/wallet/signTypedData

Specifically, for the `data.ts` file, I think we can make it as:
```
// All properties on a domain are optional
export const domain = {
  name: 'Espresso Message',
  version: '1',
  chainId: 1, // for example, ethereum mainnet
  verifyingContract: {namespace},
  // probably don't need `salt`
} as const
 
// The named list of all type definitions
export const types = {
  EspressoMessage: [
    { name: 'msgSender', type: address},
    { name: 'nonce', type: 'uint256'},
    { name: 'payload', type: 'string'},
  ],
} as const
```

**Comment by fabiooshiro** [comment]
We discussed with @tuler.eth, @Gabriel Coutinho de Paula, @pedroargento, @Milton  and concluded that we need a nonce within the "account state"

**Comment by ZzzzHui** [comment]
Yes. Similar as account states on evm. We could also make nonce sequentially incremental like ethereum does too. The other option is to make nonce random. But I prefer the former.
